// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApejvIbWrGNuz-MFgriVIDtNBgfJ8YVGk',
    appId: '1:1070521280397:web:8e3c716e6092b7c6f53fc4',
    messagingSenderId: '1070521280397',
    projectId: 'tixora-416b1',
    authDomain: 'tixora-416b1.firebaseapp.com',
    storageBucket: 'tixora-416b1.firebasestorage.app',
    measurementId: 'G-FPPGSKHKCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqARLYeOpqZiZpjYGKqPU2uS9SX2eBmFs',
    appId: '1:1070521280397:android:1b75eba4c5feaa86f53fc4',
    messagingSenderId: '1070521280397',
    projectId: 'tixora-416b1',
    storageBucket: 'tixora-416b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLIVvcWse2Y6agOCfpbtnfPU7pTEmka_g',
    appId: '1:1070521280397:ios:9a48fe666beb3b00f53fc4',
    messagingSenderId: '1070521280397',
    projectId: 'tixora-416b1',
    storageBucket: 'tixora-416b1.firebasestorage.app',
    iosBundleId: 'com.example.tixora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLIVvcWse2Y6agOCfpbtnfPU7pTEmka_g',
    appId: '1:1070521280397:ios:9a48fe666beb3b00f53fc4',
    messagingSenderId: '1070521280397',
    projectId: 'tixora-416b1',
    storageBucket: 'tixora-416b1.firebasestorage.app',
    iosBundleId: 'com.example.tixora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApejvIbWrGNuz-MFgriVIDtNBgfJ8YVGk',
    appId: '1:1070521280397:web:5b854fcc3844ec41f53fc4',
    messagingSenderId: '1070521280397',
    projectId: 'tixora-416b1',
    authDomain: 'tixora-416b1.firebaseapp.com',
    storageBucket: 'tixora-416b1.firebasestorage.app',
    measurementId: 'G-YFV9ELDGYB',
  );
}
